export interface ModelCatalogEntry {
  id: string;
  label: string;
  provider: 'openai-compatible';
  base_url: string;
  model: string;
  api_key_env: string;
}

export const MODEL_CATALOG: ModelCatalogEntry[] = [
  {
    id: 'groq-llama-3.1-8b-instant',
    label: 'Llama 3.1 8B Instant (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'llama-3.1-8b-instant',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'groq-llama-3.3-70b-versatile',
    label: 'Llama 3.3 70B Versatile (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'llama-3.3-70b-versatile',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'groq-gpt-oss-120b',
    label: 'GPT-OSS 120B (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'openai/gpt-oss-120b',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'groq-gpt-oss-20b',
    label: 'GPT-OSS 20B (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'openai/gpt-oss-20b',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'groq-compound',
    label: 'Compound (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'groq/compound',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'groq-compound-mini',
    label: 'Compound Mini (Groq)',
    provider: 'openai-compatible',
    base_url: 'https://api.groq.com/openai/v1',
    model: 'groq/compound-mini',
    api_key_env: 'GROQ_API_KEY',
  },
  {
    id: 'openrouter-gemma-4-31b',
    label: 'Gemma 4 31B (Google, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'google/gemma-4-31b-it:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-gemma-4-26b',
    label: 'Gemma 4 26B A4B (Google, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'google/gemma-4-26b-a4b-it:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-nemotron-3-ultra',
    label: 'Nemotron 3 Ultra (NVIDIA, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'nvidia/nemotron-3-ultra-550b-a55b:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-nemotron-3-super',
    label: 'Nemotron 3 Super (NVIDIA, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'nvidia/nemotron-3-super-120b-a12b:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-nemotron-3-nano-omni',
    label: 'Nemotron 3 Nano Omni Reasoning (NVIDIA, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-nemotron-3.5-lightning',
    label: 'Nemotron 3.5 Lightning (NVIDIA, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'nvidia/nemotron-3.5-lightning:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-glm-5.2',
    label: 'GLM 5.2 (Z.ai, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'z-ai/glm-5.2:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-lfm-2.5',
    label: 'LFM2.5 2.6B (Liquid AI, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'liquid/lfm-2.5-2.6b:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-inkling',
    label: 'Inkling (Thinking Machines, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'thinkingmachines/inkling:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-inkling-small',
    label: 'Inkling Small (Thinking Machines, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'thinkingmachines/inkling-small:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-laguna-s',
    label: 'Laguna S 2.1 (Poolside, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'poolside/laguna-s-2.1:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-laguna-xs',
    label: 'Laguna XS 2.1 (Poolside, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'poolside/laguna-xs-2.1:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
  {
    id: 'openrouter-dots3-note',
    label: 'Dots3-Note Preview (Dots Studio, via OpenRouter)',
    provider: 'openai-compatible',
    base_url: 'https://openrouter.ai/api/v1',
    model: 'dots-studio/dots-3-note-preview:free',
    api_key_env: 'OPENROUTER_API_KEY',
  },
];
